### ISSUE TITLE
Wrong argument definition for evaluate.py - dataset-->data

### ISSUE THREAD

**Issue by LucaLaFisca** [giacoballoccu/T-REX_TextualRecEXp#1]
In the script "evaluate.py", the argument allowing the selection of the desired dataset is not "dataset" anymore but "data" instead.

You should change it either in the Readme, or modify it in the code along with the corresponding function arguments defined as "args.data" (e.g., line 434)

**Comment by giacoballoccu** [comment]
Thanks Luca for taking the time to report this problem we proceed to correct it. Please note that an upgraded version of this framework can be found at: https://github.com/Chris1nexus/pearlm/tree/main
